config/routes.rb
Rails.application.routes.draw do

  #Rutas de prueba
  #get '/courses/:id/teams', to: 'teams#find_teams_by_course', as: 'teams_course'
  #get '/courses/all', to:'courses#all', as: 'all_courses'
  #resources :teams, :defaults => { :format => 'json' }, :except => [ :create,:update, :destroy, :edit, :index, :show, :new] do
    #collection do
      #post :create
    #end
  #end
  #post 'users/change_password/:id', to: 'users#change_password', as: 'change_password_users'
  #resources :users do
    #member do
      #post 'change_password'
    #end
  #end

  post 'commitment_prototypes', to: 'commitments_prototypes#create', as: 'commitment_prototypes'
  post 'set_token', to: 'fcm_tokens#set_token', as: 'set_token'
  resources :posts do
    resources :comments
  end
  #resources :comments
  resources :courses do
   resources :posts
  end
  #resources :posts
  resources :tasks
  resources :commitments
  resources :prototypes
  resources :products
  resources :teams
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'app#start'
  get 'dashboard', to: 'dashboard#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    collection do
      post :reset_user_password
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :users, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :find
    end
    collection do
      post :create_user
    end
    collection do
      post :update_user
    end
    collection do
      post :all # TODO: Esto deberia ser un get pero hay otra ruta por defecto que toma el request si se hace get
    end
    collection do
      post :change_password
    end
  end

 #exeptuar aquellas acciones que no son para la app 
  resources :courses, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new, :delete] do
    collection do
      post :create_course
    end
    collection do
      post :update_course
    end
    collection do
      post :find_courses_by_user
    end
    collection do
      post :search_courses_by_string
    end
    collection do
      post :all #TODO: Esto deberia ser un get pero hay otra ruta por defecto que toma el request si se hace get
    end
    collection do
      post :add_member_to_course
    end
     collection do
      post :find_members_by_course
    end
     collection do
      post :request_course_access
    end
  end

  resources :teams, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :create_team
    end
    collection do
      post :add_member_to_team
    end
    collection do
      post :delete_member
    end
    collection do
      post :find_teams_by_course
    end
    collection do
      post :find_members_by_team
    end
    collection do
      post :find_teams_by_user
    end
    collection do
      post :update_team
    end
    collection do
      post :request_team_access
    end
    collection do
      post :find_teams_by_prototype
    end
  end

  resources :products, :defaults => { :format => 'json' }, :except => [ :create,:update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :find_products_by_course
    end
    collection do
      post :find_products_by_user
    end
    collection do
      post :find_products_by_team
    end
    collection do
      post :create_product
    end
    collection do
      post :update_product
    end
  end


  #exeptuar aquellas acciones que no son para la app 
  resources :commitments, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_product
    end
    collection do
      post :find_by_team
    end
    collection do
      post :create_commitment
    end
    collection do
      post :update_commitment
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :tasks, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_commitment
    end
    collection do
      post :create_task
    end
    collection do
      post :update_task
    end
    collection do
      post :find_user_task_by_product
    end
  end

   #exeptuar aquellas acciones que no son para la app 
  resources :prototypes, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_prototype
    end
    collection do
      post :update_prototype
    end
    collection do
      post :find_by_course
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :commitments_prototypes, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_commitment_prototypes
    end
    collection do
      post :update_commitment_prototypes
    end
    collection do
      post :find_by_prototype
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :tasks_abstracts, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_task_abstract
    end
    collection do
      post :update_task_abstract
    end
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_task
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :commitment_abstracts, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_commitment_abstract
    end
    collection do
      post :update_commitment_abstract
    end
    collection do
      post :find_by_product
    end
    collection do
      post :find_by_commitment
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :product_reports, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_product_report
    end
    collection do
      post :update_product_report
    end
    collection do
      post :find_by_team
    end
    collection do
      post :find_by_product
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :notifications, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :get_notifications
    end
    collection do
      post :set_viewed
    end
    collection do
      post :set_accepted
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :course_users
  has_many :courses, through: :course_users
  has_many :tasks
  has_many :posts
  has_many :comments
  
  #Esta asosiacion es solo si la asosiacion es directa. En este caso es indirecta pues cuenta con un modelo intermedio
  #Por tal razon se utiliza has_many :course_users y has_many :users, through: :course_users
  #has_and_belongs_to_many :course_users #new


  #verificar los valores de maximum
  validates :names,  presence: true, length: { maximum: 50 }
  validates :lastnames,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 64 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password

  validates :password, presence: true, length: { maximum: 65 }, on: :create

  attr_accessor :reset_token, :rol, :img

  def as_json options=nil
    options ||= {}
    options[:methods] = ((options[:methods] || []) + [:rol, :img])
    super options
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

   # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # TODO: Esta validacion login da prolemas para las peticiones desde la app
  skip_before_action :require_login, only: [:new, :create]

  layout "main", only: [:show]

  USER_IMGS = File.join Rails.root, 'public', 'user_imgs'

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html{redirect_to user_path, notice: "User was successfully updated"}
        format.json {render json:{user: @user, status: :ok}.to_json}
        format.js
      else
        format.html { render "edit", error: "Failed to update this user"}
        format.json {render json: {info: "Failed to update this user", status: :unprocessable_entity}.to_json}
        format.js
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.destroy
        format.html{redirect_to teams_path, notice: "User delete"}
        format.json {render json: {info: "User delete", status: :ok}.to_json}
        format.js
      else
        format.html { redirect_to users_path, error: "Failed to delete this user"}
        format.json {render json: {info: "Failed to delete this user", status: :unprocessable_entity}.to_json}
        format.js
      end
    end
  end

  # get all the users
  def all
    users = User.all

    if users.any?
      users.each do |u|
        if u.image_user == "png" || u.image_user == "jpg" || u.image_user == "jpeg"
          path = "http://localhost:3000/user_imgs/#{u.id}.#{u.image_user}"
          image = open(path) { |io| io.read }
          
          u.img = Base64.encode64(image)
        end
      end
    end

    respond_to do |format|
      format.json {render json: users}
    end
  end

  # return 1 user data
  def find
    u = User.find(params[:id])

    if u != nil
      if u.image_user == "png" || u.image_user == "jpg" || u.image_user == "jpeg"
        path = "http://localhost:3000/user_imgs/#{u.id}.#{u.image_user}"
        image = open(path) { |io| io.read }
        
        u.img = Base64.encode64(image)
      end
    end

    if u != nil
      respond_to do |format|
        format.json {render json: {user: u, status: :ok}.to_json}
      end
    else
      respond_to do |format|
        format.json {render json: {user: u, status: :not_found}.to_json}

      end
    end
  end

  # create 1 user
  def create_user
    u = User.new
    u.names = params[:names]
    u.lastnames = params[:lastnames]
    u.email = params[:email]
    u.password = params[:password]
    u.password_confirmation = params[:password]
    u.initials = params[:initials]
    u.country = params[:country]
    u.city = params[:city]
    u.phone = params[:phone]
    u.sn_one = params[:sn_one]
    u.sn_two = params[:sn_two]
    u.skills = params[:skills]
    u.image_user = "45345.png" #cambiar cuando se tenga lista la traza

    #buscar registros que coincidan con el email del usario que se esta creando (params[:email])
    #y si hay alguna coincidencia devolver error
    mailLists = User.where("email = ?", u.email)

    if(mailLists.length == 0)
      if u.save

        ########## Images
        # validar si el archivo para la imagen fue cargado al post
        if(params[:img_file])
          # creamos si no existe la carpeta product_logos, definida al principio de este archivo
          FileUtils.mkdir_p USER_IMGS
          
          # Creamos el path del archivo concatenando carpeta mas nombre del archivo 
          path = File.join USER_IMGS, u.id.inspect + "." + params[:image_user]

          # Creamos el archivo y le copiamos el archivo pasado en el post 
          File.open(path, 'wb') do |f|
            f.write(params[:img_file].read)
          end

          params[:img_file] = nil
        end
        ###########

        if params[:fcm_token] != nil
          fcm_token = FcmToken.new()
          fcm_token.token = params[:fcm_token]
          fcm_token.user_id = u.id
          
          # validate ?
          fcm_token.save
        end

        @user = u
        log_in @user
        
        respond_to do |format|
          format.json {render json: {user: u, status: :created}.to_json}
          format.html{redirect_to dashboard_path}
        end
      else
        respond_to do |format|
          format.json {render json: {user: u, status: :unprocessable_entity}.to_json}
          format.html{render 'new'}
        end
      end
    
    else
      respond_to do |format|
        format.json {render json:  {info: "Este correo ya existe", status: :not_acceptable}.to_json}
        format.html{render 'new'}
      end 
    end
  end

  # update 1 user
  def update_user
    u = User.find(params[:id])

    if u == nil
      respond_to do |format|
        format.json {render json: u, status: :not_found}
      end
    end
    
    puts u.inspect

    u.names = params[:names]
    u.lastnames = params[:lastnames]
    #u.email = params[:email] #agregado
    u.password = params[:password] #agregado
    u.password_confirmation = params[:password] #agregado
    u.initials = params[:initials]
    u.country = params[:country]
    u.city = params[:city]
    u.sn_one = params[:sn_one]
    u.sn_two = params[:sn_two]
    u.phone = params[:phone]
    u.skills = params[:skills]
    u.image_user = params[:image_user]

    if u.save

      ########## Images
      # validar si el archivo para la imagen fue cargado al post
      if(params[:img_file])
        # creamos si no existe la carpeta product_logos, definida al principio de este archivo
        FileUtils.mkdir_p USER_IMGS
        
        # Creamos el path del archivo concatenando carpeta mas nombre del archivo 
        path = File.join USER_IMGS, u.id.inspect + "." + params[:image_user]

        # Creamos el archivo y le copiamos el archivo pasado en el post 
        File.open(path, 'wb') do |f|
          f.write(params[:img_file].read)
        end

        params[:img_file] = nil
      end
      ###########

      respond_to do |format|
        format.json {render json: {user: u, status: :ok}.to_json}
      end
    else
      print u.errors.full_messages # Asi se muestran los errores
      respond_to do |format|
        format.json {render json: {user: u, status: :unprocessable_entity}.to_json}
      end
    end
  end

 # change of password the 1 user
 def change_password
   u = User.find(params[:id])

   if u == nil
      respond_to do |format|
        format.json {render json: {info: "User not found", status: :not_found}.to_json}
      end
    end

    #comparo las claves 
    if(u.authenticate(params[:old_password])) 
      u.password = params[:new_password]
      u.password_confirmation = params[:new_password]

      if u.save
        respond_to do |format|
          format.json {render json: {user: u, status: :ok}.to_json}
        end
      else
        respond_to do |format|
          format.json {render json: {info: "Error saving data", status: :unprocessable_entity}.to_json}
        end
      end #cierre del if
    else
      respond_to do |format|
        format.json {render json:  {info: "Wrong password", status: :unauthorized}.to_json}
      end      
    end

 end
  # Se coloco al final para que no de peos con las acciones de la app, tambien se agrego los campos faltantes
  private
      def user_params
          #Se agrega password y password_confirmation, no password_digest.
          #En Rails dice que se puede obviar, al ser nulo el sabrá que no
          #tiene que hacer comparación, pero imagino que se mantiene password en vez de password_digest
          #Ve al link de github para que veas lo que hacen. Al final del siguiente link
          #http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password
          #Gracias por la ayuda. Recuerde que parte de lo que no puedo hacer resulta de mi poco conocimiento.
          params.require(:user).permit(:names, :lastnames, :email, :password, :password_confirmation, :initials,
           :country, :city, :phone, :sn_one, :sn_two, :skills, :image_user)
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for(@user, remote: true) do |f| %>
  <div class="modal-content">
    <h4>Editar tu perfil</h4>
    
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :names %>
      <%= f.label :names, "Nombres" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :lastnames %>
      <%= f.label :lastnames, "Apellidos" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :initials %>
      <%= f.label :initials, "Iniciales" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">email</i>
      <%= f.email_field :email %>
      <%= f.label :email, "Correo" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">phone</i>
      <%= f.telephone_field :phone%>
      <%= f.label :phone, "Telefono" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :country %>
      <%= f.label :country, "País" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :city %>
      <%= f.label :city, "Estado" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :sn_one %>
      <%= f.label :sn_one, "Red social 1" %>
    </div>
    <div class="input-field ">
      <i class="material-icons prefix input__icon--color">account_box</i>
      <%= f.text_field :sn_two %>
      <%= f.label :sn_two, "Red social 2" %>
    </div>
    <div class="input-field">
      <i class="material-icons prefix input__icon--color">mode_edit</i>
      <%= f.text_area :skills, class:"materialize-textarea" %>
      <%= f.label :skills, "Estado" %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Guardar", class: "btn" %>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat red lighten-2" >Cancelar</a> 
  </div>
<% end %>

app/views/users/_edit_password_form.html.erb
<form accept-charset="UTF-8" action="<%= change_password_users_path %>" class="col s12"
            id="change_password" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input name="authenticity_token" type="hidden"
         value="<%= form_authenticity_token %>" />
  <%= hidden_field_tag 'id', @user.id %>      
  <div class="modal-content">
    <div class="input-field ">
      <input id="old" name="old_password"
             type="password" />
      <label for="old">Contraseña actual</label>
    </div>
    <div class="input-field ">
      <input id="new"
             name="new_password" type="password" />
      <label for="new">Nueva contraseña</label>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn waves-effect waves-light" type="submit" name="change_password">Listo
    </button>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat red lighten-2" >Cancelar</a> 
  </div>
</form>

app/views/users/_form.html.erb
<%= form_for(@user, url: users_path, remote: true) do |f| %>
  <div class="modal-content">
    <h4>Edit you profile</h4>
  
    <div class="input-field ">
      <%= f.label :names %>
      <%= f.text_field :names %>
    </div>
    <div class="input-field ">
      <%= f.label :lastnames %>
      <%= f.text_field :lastnames %>
    </div>
    <div class="input-field ">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="input-field ">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="input-field ">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Edit", class: "btn" %>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat red lighten-2" >Cancel</a> 
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Registrarse') %>

<% content_for :option do %>
  <li><%= link_to "Iniciar sesión", login_path, class:"indigo-text text-accent-4"%></li>
<% end %>

<div class="container">
  <div class="row">
    <div class="col s12 l6 offset-l3">
      <h4 class="indigo-text text-accent-4">Registrarse</h4>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <%= render "shared/error_messages" %>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="center-block" style="width: 90%; padding-top: 20px;">
  <div class="row">
    <div class="col s6 m3 l3">
      <div class="wrapper-image square">
        <%= image_tag "Neuschwanstein.jpg"%>
      </div>
      <%= link_to("#modal_change_password") do %>
        <span>Editar password</span> <i class="material-icons" style="color: #85adad;">mode_edit</i>
      <% end %>
      <%= link_to("#modal_edit_profile") do %>
        <span>Editar perfil</span> <i class="material-icons" style="color: #85adad;">mode_edit</i>
      <% end %>
    </div>
    <div class="col s12 m9 l9" style="padding-top: 20px;">
      <div>
        <span style="font-weight: bold;">Name:</span> <%= current_user.names.capitalize%> 
      </div>
      <div>
        <span style="font-weight: bold;">Lastname:</span> <%= current_user.lastnames.capitalize%>
      </div>
      <div>
        <span style="font-weight: bold;">Email:</span> <%= current_user.email %>
      </div>
      <div>
        <span style="font-weight: bold;">Pasword</span>
      </div>
      <div>
        <span style="font-weight: bold;">Phone:</span> <span>0424-7811229</span>
      </div>
      <div>
        <span style="font-weight: bold;">Country:</span> <span>Venezuela</span>
      </div>
      <div>
        <span style="font-weight: bold;">State:</span> <span>Mérida</span>
      </div>
      <div>
        <span style="font-weight: bold;">Skills:</span>
        <p>Aqui una breve descripción de los talentos del usuario</p>
      </div>
      <div id="aqui">
      </div>
      <div id="aquiaqui">
        
      </div>
    </div>
  </div>
</div>
<!-- Modal Structure - Edit user -->
<div id="modal_edit_profile" class="modal">
  <%= render "edit_form" %>
</div>

<div id="modal_change_password" class="modal">
  <%= render "edit_password_form" %>
</div>

<% content_for :js do %>
  $(".sidebar").addClass('hidden-sidebar');
  $('.wrapper-submenu').hide();
<% end %>  

app/views/users/update.js.erb
var errors = <%= @user.errors.count %>
<% @user.errors.full_messages.each do |msg| %>
  console.log(<%= escape_javascript msg %>);
<% end %>

if(errors > 0){
  console.log("NO se actualizo el curso");
  
}else{

  $('#modal_edit_profile').modal('close');
}