config/routes.rb
Rails.application.routes.draw do

  #Rutas de prueba
  #get '/courses/:id/teams', to: 'teams#find_teams_by_course', as: 'teams_course'
  #get '/courses/all', to:'courses#all', as: 'all_courses'
  #resources :teams, :defaults => { :format => 'json' }, :except => [ :create,:update, :destroy, :edit, :index, :show, :new] do
    #collection do
      #post :create
    #end
  #end
  #post 'users/change_password/:id', to: 'users#change_password', as: 'change_password_users'
  #resources :users do
    #member do
      #post 'change_password'
    #end
  #end

  post 'commitment_prototypes', to: 'commitments_prototypes#create', as: 'commitment_prototypes'
  post 'set_token', to: 'fcm_tokens#set_token', as: 'set_token'
  resources :posts do
    resources :comments
  end
  #resources :comments
  resources :courses do
   resources :posts
  end
  #resources :posts
  resources :tasks
  resources :commitments
  resources :prototypes
  resources :products
  resources :teams
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'app#start'
  get 'dashboard', to: 'dashboard#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    collection do
      post :reset_user_password
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :users, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :find
    end
    collection do
      post :create_user
    end
    collection do
      post :update_user
    end
    collection do
      post :all # TODO: Esto deberia ser un get pero hay otra ruta por defecto que toma el request si se hace get
    end
    collection do
      post :change_password
    end
  end

 #exeptuar aquellas acciones que no son para la app 
  resources :courses, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new, :delete] do
    collection do
      post :create_course
    end
    collection do
      post :update_course
    end
    collection do
      post :find_courses_by_user
    end
    collection do
      post :search_courses_by_string
    end
    collection do
      post :all #TODO: Esto deberia ser un get pero hay otra ruta por defecto que toma el request si se hace get
    end
    collection do
      post :add_member_to_course
    end
     collection do
      post :find_members_by_course
    end
     collection do
      post :request_course_access
    end
  end

  resources :teams, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :create_team
    end
    collection do
      post :add_member_to_team
    end
    collection do
      post :delete_member
    end
    collection do
      post :find_teams_by_course
    end
    collection do
      post :find_members_by_team
    end
    collection do
      post :find_teams_by_user
    end
    collection do
      post :update_team
    end
    collection do
      post :request_team_access
    end
    collection do
      post :find_teams_by_prototype
    end
  end

  resources :products, :defaults => { :format => 'json' }, :except => [ :create,:update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :find_products_by_course
    end
    collection do
      post :find_products_by_user
    end
    collection do
      post :find_products_by_team
    end
    collection do
      post :create_product
    end
    collection do
      post :update_product
    end
  end


  #exeptuar aquellas acciones que no son para la app 
  resources :commitments, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_product
    end
    collection do
      post :find_by_team
    end
    collection do
      post :create_commitment
    end
    collection do
      post :update_commitment
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :tasks, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_commitment
    end
    collection do
      post :create_task
    end
    collection do
      post :update_task
    end
    collection do
      post :find_user_task_by_product
    end
  end

   #exeptuar aquellas acciones que no son para la app 
  resources :prototypes, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_prototype
    end
    collection do
      post :update_prototype
    end
    collection do
      post :find_by_course
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :commitments_prototypes, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_commitment_prototypes
    end
    collection do
      post :update_commitment_prototypes
    end
    collection do
      post :find_by_prototype
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :tasks_abstracts, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_task_abstract
    end
    collection do
      post :update_task_abstract
    end
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_task
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :commitment_abstracts, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_commitment_abstract
    end
    collection do
      post :update_commitment_abstract
    end
    collection do
      post :find_by_product
    end
    collection do
      post :find_by_commitment
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :product_reports, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_product_report
    end
    collection do
      post :update_product_report
    end
    collection do
      post :find_by_team
    end
    collection do
      post :find_by_product
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :notifications, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :get_notifications
    end
    collection do
      post :set_viewed
    end
    collection do
      post :set_accepted
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  #layout :resolve_layout
  layout "main"

  # Usado para comunicarse con el sistema de notificaciones
  require 'net/http'

  #skip_before_action :verify_authenticity_token #esto es para hacer pruebas, preguntar antes si necesitas eliminarlo

  COURSES_LOGOS = File.join Rails.root, 'public', 'courses_logos'

  def index
    @course = Course.new
    courses = Course.joins(:course_users).where(course_users: {user_id: current_user.id}).order('created_at DESC')
    @my_courses = Array.new
    courses.each do |course|
      c_u = CourseUser.where(course_id: course.id)
      course.studentsAmount = c_u.length - 1
      c_u.each do |cu|
        if cu.rol == "CEO"
          course.ceo = cu.user.names
          course.ceo_id = cu.user.id
        end
      end
      @my_courses << course
    end  
  end

  def show
    @course = Course.find(params[:id])
    @team = Team.new
    @prototype = Prototype.new
  end

  def new
    @course = Course.new
  end

  def create

    @courses = Array.new
    for i in 1..(Integer(params[:course][:section]))
      @course = Course.new(course_params);
      @course.section = i
      if @course.save
        @course_user = CourseUser.new
        @course_user.rol = "CEO"
        @course_user.user = current_user
        @course_user.course = @course
        
        respond_to do |format|
          if @course_user.save
            @courses << @course
            format.html{redirect_to dashboard_path}
            format.js
          else
            format.html { render "new" }
            format.js
          end
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    
    respond_to do |format|
      if @course.update_attributes(course_params)
        format.html{redirect_to courses_path, notice: "Course was successfully updated"}
        format.json {render json:{team: @course, status: :ok}.to_json}
        format.js
      else
        format.html { render "edit", error: "Failed to update this course"}
        format.json {render json: {info: "Failed to update this course", status: :unprocessable_entity}.to_json}
        format.js
      end
    end
  end

  def destroy
    @course = Course.find(params[:id])
    respond_to do |format|
      if @course.destroy
        format.html{redirect_to courses_path, notice: "Course delete"}
        format.json {render json: {info: "Course delete", status: :ok}.to_json}
        format.js
      else
        format.html { redirect_to courses_path, error: "Failed to delete this course"}
        format.json {render json: {info: "Failed to delete this course", status: :unprocessable_entity}.to_json}
        format.js
      end
    end
  end

  # get all the courses
  def all
    list = Array.new

    Course.all.each do |course|
      auxList = CourseUser.where(:course => course) # Y para obtener el numero de miembros de ese curso, buscamos todos los registros
                                                    # en CourseUSer donde aparece dicho curso (miembros)
      course.studentsAmount = auxList.length - 1

      #Esta variable es una bandera para saber si el usuario es miembro o no, si es que nos lo pasan
      is_member = false

      # Encontrar el CEO del curso en el cual aparece el usuario
      # Buscar el registro del CEO en la lista de registros en CourseUSer donde aparece dicho curso (miembros)
      auxList.each do |auxCU|  
        if auxCU.rol == "CEO" # Es decir donde el rol es CEO
          course.ceo = auxCU.user.names + " " + auxCU.user.lastnames
          course.ceo_id = auxCU.user.id
        end

        # si nos pasan el id de usuario, lo comparamos con cada miembro, y si lo conseguimos ponemos
        # la bandera en true
        if(params[:user_id] != nil and auxCU.user.id == Integer(params[:user_id]))
          is_member = true;
        end
      end

      course.is_member = is_member

      if course.logo == "png" || course.logo == "jpg" || course.logo == "jpeg"
        path = "http://localhost:3000/courses_logos/#{course.id}.#{course.logo}"
        image = open(path) { |io| io.read }
        
        course.logo_file = Base64.encode64(image)
      end

      list << course
    end

    if (list != nil)
      @courses_list = list
      respond_to do |format|
        format.json {render json: {courses: list, status: :ok}.to_json}
        format.js
      end
    else
      respond_to do |format|
        format.json {render json: {info: "Unprocessable entity", status: :unprocessable_entity}.to_json}
        format.js
      end
    end
  end

  #create 1 course
  def create_course

    u = User.find(params[:user_id])
    #verificando que el usuario existe
    if u == nil
      respond_to do |format|
        format.json {render json:  {info: "Not found user", status: :not_found}.to_json}
      end
    end

    created_courses = Array.new
    
    for i in 0..(Integer(params[:section]) - 1)
      c = Course.new
      c.name = params[:name]
      c.initials = params[:initials]
      c.period_type = params[:period_type]
      c.section = i+1
      c.category = params[:category]
      c.institute = params[:institute]
      c.content = params[:content]
      c.privacy = params[:privacy]
      c.inscriptions_activated = params[:inscriptions_activated]
      c.evaluate_teacher = params[:evaluate_teacher]
      c.strict_mode_isa = params[:strict_mode_isa]
      c.code_confirmed = params[:code_confirmed]
      c.logo = params[:logo]
      c.period_length = params[:period_length]
      c.description = params[:description]

      if c.save
        cu = CourseUser.new(:user => u,:course => c,:rol => "CEO")

        if cu.save

          ########## Images
          # validar si el archivo para la imagen fue cargado al post
          if(params[:logo_file])
            # creamos si no existe la carpeta product_logos, definida al principio de este archivo
            FileUtils.mkdir_p COURSES_LOGOS
            
            # Creamos el path del archivo concatenando carpeta mas nombre del archivo 
            path = File.join COURSES_LOGOS, c.id.inspect + "." + params[:logo]

            # Creamos el archivo y le copiamos el archivo pasado en el post 
            File.open(path, 'wb') do |f|
              f.write(params[:logo_file].read)
            end

            params[:logo_file] = nil
          end
          ###########

          created_courses << c
          next
        else
          respond_to do |format|
            format.json {render json:  {info: "Curso-Usuario no creado", course: c, status: :unprocessable_entity}.to_json}
          end
        end
      else
        respond_to do |format|
          format.json  {render json: {course: c, status: :unprocessable_entity}.to_json}
        end
      end
    end #for

    respond_to do |format|

      format.json {render json: {course: created_courses, status: :ok}.to_json} ### revisar, se cambio el nombre a plural
    end
  end  #action

   #update 1 course
  def update_course
    c = Course.find(params[:id])

    if c == nil
      respond_to do |format|
        format.json {render json: c, status: :not_found}
      end
    end

    c.name = params[:name]
    c.initials = params[:initials]
    c.period_type = params[:period_type]
    c.section = params[:section]
    c.category = params[:category]
    c.institute = params[:institute]
    c.content = params[:content]
    c.privacy = params[:privacy]
    c.inscriptions_activated = params[:inscriptions_activated]
    c.evaluate_teacher = params[:evaluate_teacher]
    c.strict_mode_isa = params[:strict_mode_isa]
    c.code_confirmed = params[:code_confirmed]
    c.logo = params[:logo]
    c.period_length = params[:period_length]
    c.description = params[:description]

    if c.save

      ########## Images
      # validar si el archivo para la imagen fue cargado al post
      if(params[:logo_file])
        # creamos si no existe la carpeta product_logos, definida al principio de este archivo
        FileUtils.mkdir_p COURSES_LOGOS
        
        # Creamos el path del archivo concatenando carpeta mas nombre del archivo 
        path = File.join COURSES_LOGOS, c.id.inspect + "." + params[:logo]

        # Creamos el archivo y le copiamos el archivo pasado en el post 
        File.open(path, 'wb') do |f|
          f.write(params[:logo_file].read)
        end

        params[:logo_file] = nil
      end
      ###########

      respond_to do |format|
        format.json {render json: {course: c, status: :ok}.to_json}
      end
    else
      respond_to do |format|
        format.json  {render json: {course: c, status: :unprocessable_entity}.to_json}
      end
    end
  end

  #Obtener todos los cursos de un usuario
  def find_courses_by_user
    u = User.find(params[:id])
    if u == nil
      respond_to do |format|
        format.json {render json: {info: "User not found", status: :not_found}.to_json}
      end
    end

    list = Array.new

    #Buscar los registros de CourseUSer de el usuario (u)
    CourseUser.where(:user => u).each do |cu|   # Para cada registro en el que aparece el usuario
      course = cu.course  #Course.find(cu.course.id)  # Obtener el curso
      auxList = CourseUser.where(:course => course) # Y para obtener el numero de miembros de ese curso, buscamos todos los registros
                                                    # en CourseUSer donde aparece dicho curso (miembros)
      course.studentsAmount = auxList.length - 1

      # Encontrar el CEO del curso en el cual aparece el usuario
      if cu.rol == "CEO"  #Dado que estos registros de CourseUser son de el usuario actual, si el rol es CEO implica que u es el CEO
        course.ceo = u.names + " " + u.lastnames
        course.ceo_id = u.id

app/helpers/courses_helper.rb
module CoursesHelper

  #Retorna true si el usuario es CEO dentro del curso
  def is_ceo?(user_id, course_id)
    course_user = CourseUser.where(user_id: user_id, rol:"CEO", course_id:course_id)
    course_user.any?
  end

  #Retorna true si el usuario es Miembro dentro del curso
  def is_member?(user_id, course_id)
    course_user = CourseUser.where(user_id: user_id, course_id:course_id)
    course_user.any?
  end
end

app/views/courses/_course.html.erb
<%= link_to( course_path course.id ) do %>  
  <div class="wrapper-card">
    <div class="card-course">
      <div class="wrapper-img">
        <%= image_tag "Neuschwanstein.jpg"%>
      </div>
      <div class="wrapper-content">
        <div class="content">
          <p><%= course.name %></p>
          <p><%= course.description %></p>
          <p><%= course.ceo %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/_course_sidebar.html.erb
<div style="width: 100%; height: 100%; overflow: auto;">
  <div class="wrapper-image-square">
    <%= image_tag "Neuschwanstein.jpg"%>
  </div>
  <div style="position: relative; padding: 20px;">
    <% if is_ceo? current_user.id, @course.id %>
      <%= link_to( "#modal_edit_course", class:"btn-floating blue", style:"position: absolute; top: -20px; right: 5px;") do %>
        <i class="material-icons">mode_edit</i> 
      <% end %>
    <% else %>
      <% if !is_member? current_user.id, @course.id %>

        <form accept-charset="UTF-8" action="<%= request_course_access_courses_path %>" method="post" id="add_member_to_course" >
          <input name="utf8" type="hidden" value="&#x2713;" />
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
          <%= hidden_field_tag :user_id, current_user.id %>
          <%= hidden_field_tag :course_id, @course.id %>
          <%= button_tag(name: "add_member", :class => "btn-floating blue", :style=>"position: absolute; top: -20px; right: 5px;") do %>
            <i class="material-icons">done</i>
          <% end %>
        </form>

      <% end %>
    <%end%>
    <div style="margin-bottom: : 10px;">
      <span style="font-weight: bold; color: #424242; font-size: 28px;"><%= @course.name%></span>
    </div>
    <div class="">
      <%= @course.description %>
    </div>
  </div>
</div>

app/views/courses/_edit_form.html.erb
<%= form_for(@course, remote: true) do |f| %>
  <div class="modal-content">
    <div class="input-field ">
      <%= f.text_field :name %>
      <%= f.label :name, "Nombre" %>
    </div>
    <div class="input-field ">
      <%= f.text_field :description %>
      <%= f.label :description, "Descripción" %>
    </div>
    <div class="switch">
      <label>
        ISA
        <%= f.check_box :strict_mode_isa%>
        <span class="lever"></span>
      </label>
    </div>
    <div class="switch">
      <label>
        Evaluar profesor
        <%= f.check_box :evaluate_teacher%>
        <span class="lever"></span>
      </label>
    </div>
    <div class="switch">
      <label>
        Codigo de confirmación
        <%= f.check_box :code_confirmed%>
        <span class="lever"></span>
      </label>
    </div>
    <div class="switch">
      <label>
        Inscripciones activas
        <%= f.check_box :inscriptions_activated%>
        <span class="lever"></span>
      </label>
    </div>
    <p>
      <%= f.radio_button :privacy, "public" %>
      <%= label_tag(:course_privacy_public, "Público") %>
    </p>
    <p>
      <%= f.radio_button :privacy, "private" %>
      <%= label_tag(:course_privacy_private, "Privado") %>
    </p>
  </div>
  <div class="modal-footer">
    <%= f.submit "Guardar", class: "btn" %>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat grey lighten-1" >Cancelar</a> 
  </div>
<% end %>

app/views/courses/_form.html.erb
<%= form_for(@course, remote: true) do |f| %>
  <div class="modal-content">
    <div class="input-field ">
      <%= f.text_field :name %>
      <%= f.label :name, "Nombre" %>
    </div>
    <div class="input-field ">
      <%= f.text_field :description %>
      <%= f.label :description, "Descripción" %>
    </div>
    <div class="switch">
      <label>
        ISA
        <%= f.check_box :strict_mode_isa%>
        <span class="lever"></span>
      </label>
    </div>
    <div class="switch">
      <label>
        Evaluar profesor
        <%= f.check_box :evaluate_teacher%>
        <span class="lever"></span>
      </label>
    </div>
    <div class="switch">
      <label>
        Codigo de confirmación
        <%= f.check_box :code_confirmed%>
        <span class="lever"></span>
      </label>
    </div>
    <div class="switch">
      <label>
        Inscripciones activas
        <%= f.check_box :inscriptions_activated%>
        <span class="lever"></span>
      </label>
    </div>
    <p>
      <%= f.radio_button :privacy, "public" %>
      <%= label_tag(:course_privacy_public, "Público") %>
    </p>
    <p>
      <%= f.radio_button :privacy, "private" %>
      <%= label_tag(:course_privacy_private, "Privado") %>
    </p>
    <div class="input-field">
      <%= f.select :section, options_for_select([['1', 1], ['2', 2], ['3', 3]], 1) %>
      <label>Secciones</label>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Guardar", class: "btn" %>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat grey lighten-1" >Cancelar</a> 
  </div>
<% end %>

app/views/courses/all.js.erb
console.log("Solicitando todos los cursos ESTA ES UNA PRUEBA");
<% @list.each do |msg| %>  
    //$("#member").append("<li><%= msg %></li>");
    $("#member").prepend("<%= j render msg %>");  
<% end %>

app/views/courses/create.js.erb
var error= <%= @course_user.errors.count %>;

if(error>0){
  console.log("NO se creo el curso");
  
}else{
  
  console.log("Se creo el curso");
  $('#msm_new_course').hide();
  $('#modal_new_course').modal_success(); // Función definida en course.js
  $("#my_courses").prepend("<%= j render @courses %>");  
}

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/index.html.erb
<% content_for :bar_option do %> 
  <ul class="tabs center-block">
    <li class="tab"><a class="active" href="#my_courses" style="outline: none;">creados</a></li>
    <li class="tab"><a href="#member" style="outline: none;">asociados</a></li>
    <li class="tab"><a href="#all_courses" id="get_all_courses" style="outline: none;">todos</a></li>
  </ul>      
<% end %>

<div id="my_courses">
  <% if @my_courses.any? %>
    <% count_course = 0%>
    <% @my_courses.each do |course|%>
      <%if course.ceo_id == current_user.id %>
        <%= render course %>
        <%count_course +=1 %>
      <%end%>
    <%end%>
    <% if count_course == 0 %>
      <div id="msm_new_course">
        <h4 class="center" style="color: #94b8b8; font-weight: bold;">Crea un curso</h4>
        <div class="center">
          <a href="#modal_new_course" style="outline: none; display: inline-flex; flex-direction: column;">
            <i class="material-icons circle center" style="color: #85adad; font-size: 56px;">add_circle_outline</i>
            <span style="color: #85adad; font-size: 28px;">Nuevo curso</span>
          </a>
        </div>
      </div>
    <%else%>
      <div class="fixed-action-btn">
        <a href="#modal_new_course" class="btn-floating btn-large tooltipped indigo"
        data-position="left" data-delay="50" data-tooltip="Nuevo curso">
          <i class="large material-icons">add</i>
        </a>
      </div>
    <%end%>
  <%else%>
    <div id="msm_new_course">
      <h4 class="center" style="color: #94b8b8; font-weight: bold;">Crea un curso</h4>
      <div class="center">
        <a href="#modal_new_course" style="outline: none; display: inline-flex; flex-direction: column;">
          <i class="material-icons circle center" style="color: #85adad; font-size: 56px;">add_circle_outline</i>
          <span style="color: #85adad; font-size: 28px;">Nuevo curso</span>
        </a>
      </div>
    </div>    
  <%end%>
</div>

<!-- Modal Structure - New course -->
<div id="modal_new_course" class="modal">
  <h5 style="padding-left: 20px;">Nuevo curso</h5>
  <%= render "form" %>
</div>
</div>
<div id="member">
  <% if @my_courses.any? %>
    <% count_course = 0%>
    <% @my_courses.each do |course|%>
      <%if course.ceo_id != current_user.id %>
        <%= render course %>
        <%count_course +=1 %>
      <%end%>
    <%end%>
    <%if count_course == 0%>
      <h4 class="center" style="color: #94b8b8; font-weight: bold;">No estás asociado a ningun curso</h4> 
    <%end%>
  <% else %>
    <h4 class="center" style="color: #94b8b8; font-weight: bold;">No estás asociado a ningun curso</h4>
  <% end %>
</div>
<div id="all_courses">

</div>

<% content_for :js do %>
  $(".sidebar").addClass('hidden-sidebar');
  $('#hamburger_menu').hide();
<% end %>  

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/show.html.erb
<% content_for :parax_option do %>
  <div class="parallax-container hide-on-med-and-up">
    <div class="parallax"><%= image_tag "Neuschwanstein.jpg"%></div>
    <span style="position: absolute; bottom: 0; font-weight: bold; font-size: 20px;color: #424242; padding: 0 10px; background-color: rgba(204, 255, 255, 0.4)"><%= @course.name%></span>
  </div>
<% end %>

<% content_for :sidebar_option do %>
  <%= render "course_sidebar" %>
<% end %>

<% content_for :bar_option do %>
  <ul class="tabs">
    <li class="tab hide-on-med-and-up"><a href="#information" style="outline: none;">información</a></li>
    <li class="tab"><a class="active" href="#teams" style="outline: none;">equipos</a></li>
    <li class="tab"><a id="get_course_members" href="#course_members" style="outline: none;">miembros</a></li>
    <li class="tab"><a id="get_course_products" href="#course_products" style="outline: none;">productos</a></li>
    <li class="tab"><a id="get_course_products_prototypes" href="#course_products_prototypes" style="outline: none;">productos prototipos</a></li>
    <!--<li class="tab"><a href="posts" style="outline: none;">muro</a></li>-->
    <li class="tab"><%= link_to "muro", course_posts_path(@course.id), target:"_self", style:"outline: none;" %></li>
  </ul>      
<% end %>

<div id="course_id" data-id = "<%= @course.id %>" style="display: none;"></div>

<div id="information" class="hide-on-med-and-up">
  <h4><%= @course.name%></h4>
  <h5>Descripción del curso</h5>
  <p><%= @course.description %></p>
  <% if is_ceo? current_user.id, @course.id %>
    <%= link_to "Editar", edit_course_path %>
  <%end%>
</div>

<div id="teams">
  <ul class="collection"> 
  </ul>
  <!-- New Team -->
  <% if is_member?(current_user.id, @course.id) && !has_team?(current_user.id, @course.id) && !is_ceo?(current_user.id, @course.id)%>
    <div id="link_new_team" class="fixed-action-btn">
      <a href="#modal_new_team" class="btn-floating btn-large tooltipped indigo"
      data-position="left" data-delay="50" data-tooltip="Nuevo equipo">
        <i class="large material-icons">add</i>
      </a>
    </div>
  <% end %>
</div>

<div id="course_members">
  <h4>Miembros del curso</h4>
  <ul class="collection">
  </ul>
</div>

<div id="course_products">
  <h4>Productos del curso</h4>
  <ul class="collection"> 
  </ul>
</div>

<div id="course_products_prototypes">
  <h4>Productos prototipos del curso</h4>
  <ul class="collection"> 
  </ul>
  <!-- New Product Prototype -->
  <% if is_ceo?(current_user.id, @course.id)%>
    <div id="link_new_product_prototype" class="fixed-action-btn">
      <a href="#modal_new_prototype" class="btn-floating btn-large tooltipped indigo"
      data-position="left" data-delay="50" data-tooltip="Nuevo prototipo">
        <i class="large material-icons">add</i>
      </a>
    </div>
  <% end %>
</div>

<!-- Modal Structure - Edit course -->
<div id="modal_edit_course" class="modal">
  <h5 style="padding-left: 20px;">Editar curso</h5>
  <%= render "edit_form" %>
</div>

<!-- Modal Structure - New team -->
<div id="modal_new_team" class="modal">
  <h5 style="padding-left: 20px;">Nuevo equipo</h5>
  <%= render "teams/form" %>
</div>

<!-- Modal Structure - New product_prototype -->
<div id="modal_new_prototype" class="modal">
  <h5 style="padding-left: 20px;">Nuevo producto prototipo</h5>
  <%= render "prototypes/form" %>
</div>

<% content_for :js do %>
  $(".sidebar").addClass('hide-sidebar');
<% end %>

app/views/courses/update.js.erb
var error= <%= @course.errors.count %>;

if(error>0){
  console.log("NO se creo el curso");
  
}else{

  $('#modal_edit_course').modal('close'); // Función definida en course.js
  $('.sidebar').empty();
  $('.sidebar').html("<%= escape_javascript (render partial: 'course_sidebar') %>"); 
  var $toastContent = $('<span>Curso actualizado correctamente</span>');
  Materialize.toast($toastContent, 3000);
}