config/routes.rb
Rails.application.routes.draw do

  #Rutas de prueba
  #get '/courses/:id/teams', to: 'teams#find_teams_by_course', as: 'teams_course'
  #get '/courses/all', to:'courses#all', as: 'all_courses'
  #resources :teams, :defaults => { :format => 'json' }, :except => [ :create,:update, :destroy, :edit, :index, :show, :new] do
    #collection do
      #post :create
    #end
  #end
  #post 'users/change_password/:id', to: 'users#change_password', as: 'change_password_users'
  #resources :users do
    #member do
      #post 'change_password'
    #end
  #end

  post 'commitment_prototypes', to: 'commitments_prototypes#create', as: 'commitment_prototypes'
  post 'set_token', to: 'fcm_tokens#set_token', as: 'set_token'
  resources :posts do
    resources :comments
  end
  #resources :comments
  resources :courses do
   resources :posts
  end
  #resources :posts
  resources :tasks
  resources :commitments
  resources :prototypes
  resources :products
  resources :teams
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'app#start'
  get 'dashboard', to: 'dashboard#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update] do
    collection do
      post :reset_user_password
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :users, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :find
    end
    collection do
      post :create_user
    end
    collection do
      post :update_user
    end
    collection do
      post :all # TODO: Esto deberia ser un get pero hay otra ruta por defecto que toma el request si se hace get
    end
    collection do
      post :change_password
    end
  end

 #exeptuar aquellas acciones que no son para la app 
  resources :courses, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new, :delete] do
    collection do
      post :create_course
    end
    collection do
      post :update_course
    end
    collection do
      post :find_courses_by_user
    end
    collection do
      post :search_courses_by_string
    end
    collection do
      post :all #TODO: Esto deberia ser un get pero hay otra ruta por defecto que toma el request si se hace get
    end
    collection do
      post :add_member_to_course
    end
     collection do
      post :find_members_by_course
    end
     collection do
      post :request_course_access
    end
  end

  resources :teams, :defaults => { :format => 'json' }, :except => [:create, :update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :create_team
    end
    collection do
      post :add_member_to_team
    end
    collection do
      post :delete_member
    end
    collection do
      post :find_teams_by_course
    end
    collection do
      post :find_members_by_team
    end
    collection do
      post :find_teams_by_user
    end
    collection do
      post :update_team
    end
    collection do
      post :request_team_access
    end
    collection do
      post :find_teams_by_prototype
    end
  end

  resources :products, :defaults => { :format => 'json' }, :except => [ :create,:update, :destroy, :edit, :index, :show, :new] do
    collection do
      post :find_products_by_course
    end
    collection do
      post :find_products_by_user
    end
    collection do
      post :find_products_by_team
    end
    collection do
      post :create_product
    end
    collection do
      post :update_product
    end
  end


  #exeptuar aquellas acciones que no son para la app 
  resources :commitments, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_product
    end
    collection do
      post :find_by_team
    end
    collection do
      post :create_commitment
    end
    collection do
      post :update_commitment
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :tasks, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_commitment
    end
    collection do
      post :create_task
    end
    collection do
      post :update_task
    end
    collection do
      post :find_user_task_by_product
    end
  end

   #exeptuar aquellas acciones que no son para la app 
  resources :prototypes, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_prototype
    end
    collection do
      post :update_prototype
    end
    collection do
      post :find_by_course
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :commitments_prototypes, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_commitment_prototypes
    end
    collection do
      post :update_commitment_prototypes
    end
    collection do
      post :find_by_prototype
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :tasks_abstracts, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_task_abstract
    end
    collection do
      post :update_task_abstract
    end
    collection do
      post :find_by_user
    end
    collection do
      post :find_by_task
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :commitment_abstracts, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_commitment_abstract
    end
    collection do
      post :update_commitment_abstract
    end
    collection do
      post :find_by_product
    end
    collection do
      post :find_by_commitment
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :product_reports, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :create_product_report
    end
    collection do
      post :update_product_report
    end
    collection do
      post :find_by_team
    end
    collection do
      post :find_by_product
    end
  end

  #exeptuar aquellas acciones que no son para la app 
  resources :notifications, :defaults => { :format => 'json' }, :except => [:create, :update] do
    collection do
      post :get_notifications
    end
    collection do
      post :set_viewed
    end
    collection do
      post :set_accepted
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  #has_many :commitments
  has_many :product_users
  has_many :course_users, through: :product_users
  has_many :commitments
  belongs_to :team
  belongs_to :prototype, optional: true
  has_one :product_report


  attr_accessor :logo_img, :team_name, :execution # Agregar cualquier otro al metodo as_json de abajo

  # Sobreescribir la funcion as_json
  def as_json options=nil
    options ||= {}
    options[:methods] = ((options[:methods] || []) + [:logo_img, :team_name, :execution])
    super options
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  layout "main"

  PRODUCT_LOGOS = File.join Rails.root, 'public', 'products_logos'

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @commitment = Commitment.new
  end

  def new
    @product = Product.new
  end

  def create
    #El mismo caso que con course-teams
    #yo puedo enviar el id de team desde el formulario como hidden
    @product = Product.new(product_params);

    #Agregar id si se trata de un prototipo
    if params[:use_prototype] != nil && params[:use_prototype] == 'true'
      @product.prototype_id = params[:prototype_id]
    end  
    respond_to do |format|
      if @product.save

        currUser = User.find(current_user)

        if params[:use_prototype] != nil && params[:use_prototype] == 'true'

          prototype = Prototype.find(params[:prototype_id])

          # Obtener los compromisos del prototipo y crear los mismos compromisos para el producto
          commitment_prototypes = prototype.commitment_prototypes
          commitment_prototypes.each do |cp|
            @commitment = Commitment.new()
            @commitment.description = cp.description
            @commitment.deadline = cp.deadline
            @commitment.execution = 0
            @commitment.count = 0

            @commitment.user = currUser.id
            @commitment.product = @product

            # Validate if the user and the product were found
            if currUser == nil
                format.json {render json: { info: "User not found",  status: :not_found}.to_json}
                format.js
            else  # usuario encontrado
              if @commitment.save
                format.html{redirect_to products_path , notice: "Product was created successfully"}
                format.json {render json: {product: product, status: :ok}.to_json}
                format.js
              else  # error con commitment.save
                format.json {render json: { info: "Error creating commitment",  status: :unprocessable_entity}.to_json}
                format.js
              end
            end
          end # fin del commitent_prototypes.each 
        end

        format.html{redirect_to products_path , notice: "Product was created successfully"}
        format.json {render json: {product: @product, status: :ok}.to_json}
        format.js
      else
        format.html { render "new", error: "The product was not created" }
        format.json {render json: {product: @product,  status: :unprocessable_entity}.to_json }
        format.js
      end
    end
  end

  def create_product
    product = Product.new();
    product.name = params[:name]
    product.description = params[:description]
    product.logo = params[:logo]  #extension
    product.team_id = params[:team_id]
    product.initials = params[:initials]
    
    if params[:use_prototype] != nil && params[:use_prototype] == 'true'
      prototype = Prototype.find(params[:prototype_id])
      product.prototype = prototype
    end

    respond_to do |format|
      if product.save

        ########## Images
        # validar si el archivo para la imagen fue cargado al post
        if(params[:logo_file])
          # creamos si no existe la carpeta product_logos, definida al principio de este archivo
          FileUtils.mkdir_p PRODUCT_LOGOS
          
          # Creamos el path del archivo concatenando carpeta mas nombre del archivo 
          path = File.join PRODUCT_LOGOS, product.id.inspect + "." + params[:logo]

          # Creamos el archivo y le copiamos el archivo pasado en el post 
          File.open(path, 'wb') do |f|
            f.write(params[:logo_file].read)
          end

          params[:logo_file] = nil
        end
        ###########

        ceo_id = 0; 
        # Obtener user del ceo para enviarle la notificacion
        auxList = CourseUser.where(:course => product.team.course)
        auxList.each do |auxCU|  
          if auxCU.rol == "CEO" # Es decir donde el rol es CEO
            ceo_id = auxCU.user.id
          end
        end

        currUser = User.find(params[:user_id])

        ###############################
        tokens = FcmToken.where(:user_id => ceo_id)
 
        if tokens.length > 0 && tokens[0] != nil
          uri = URI('https://fcm.googleapis.com/fcm/send')
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true
          req = Net::HTTP::Post.new(uri.path, initheader = {'Content-Type' =>'application/json', 'Authorization' => 'key=AAAAe3BYdgo:APA91bF13EtVd07IZdv-9XTSATSwd-d1J1n2gKjVWpppTuz7Uj1R2hnwTCL3ioL4e7F4YVhU-iMzDI66Czu9mRT3A9sqQ-HVmb24wyda-lwEukaL7eCLjJHAvnEsi8foZ2_Bsh44wtN8'})
 
          req.body = {:to => tokens[0].token,
           :notification => {:title => 'Han creado un producto en uno de tus equipos', :body => currUser.names + ' ha creado un producto en el equipo ' + product.team.name + ' del curso ' + product.team.course.name},
            :data => {:type => 'NEW_PRODUCT', :user_id => currUser.id, :user_name => currUser.names, :course_id => product.team.course.id, :course_name => product.team.course.name, :team_id => product.team.id, :team_name => product.team.name, :product_id => product.id}}.to_json
 
          response = http.request(req)
          ##############################

          notification = Notification.new
          notification.user_id = ceo_id
          notification.noti_type = 'NEW_PRODUCT'
          notification.noti_user_id = currUser.id
          notification.user_name = currUser.names
          notification.course_id = product.team.course.id
          notification.course_name = product.team.course.name
          notification.team_id = product.team.id
          notification.team_name = product.team.name
          
          notification.save
        end

        # Verofocar si el producto esta basado en un prototipo
        if params[:use_prototype] != nil && params[:use_prototype] == 'true'
          prototype = Prototype.find(params[:prototype_id])

          # Obtener el compromiso de dicho prototipo y crear un compromiso para cada uno
          commitment_prototypes = CommitmentPrototype.where(:prototype => prototype);
          commitment_prototypes.each do |cp|
            commitment = Commitment.new()
            commitment.description = cp.description
            commitment.deadline = cp.deadline
            commitment.execution = 0
            commitment.count = 0

            commitment.commitment_prototype = cp
            commitment.user = currUser.id
            commitment.product = product

            # Validate if the user and the product were found
            if currUser == nil
                format.json {render json: { info: "User not found",  status: :not_found}.to_json}
            else  # usuario encontrado
              if commitment.save
                format.html{redirect_to products_path , notice: "Product was created successfully"}
                format.json {render json: {product: product, status: :ok}.to_json}
                format.js
              else  # error con commitment.save
                format.json {render json: { info: "Error creating commitment",  status: :unprocessable_entity}.to_json}
              end
            end
          end # fin del commitent_prototypes.each 
        else  # No se uso prototipos
          format.html{redirect_to products_path , notice: "Product was created successfully"}
          format.json {render json: {product: product, status: :ok}.to_json}
          format.js
        end
      else  # error con product.save
          format.html { render "new", error: "The product was not created" }
          format.json {render json: {product: product,  status: :bad_request}.to_json }
          format.js
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update_product
    product = Product.find(params[:id])
    product.name = params[:name]
    product.description = params[:description]
    product.logo = params[:logo] # extension
    product.initials = params[:initials]
    #product.team_id = params[:team_id]

    respond_to do |format|
      if product.save

        ########## Images
        # validar si el archivo para la imagen fue cargado al post
        if(params[:logo_file])
          # creamos si no existe la carpeta product_logos, definida al principio de este archivo
          FileUtils.mkdir_p PRODUCT_LOGOS
          
          # Creamos el path del archivo concatenando carpeta mas nombre del archivo 
          path = File.join PRODUCT_LOGOS, product.id.inspect + "." + params[:logo]

          # Creamos el archivo y le copiamos el archivo pasado en el post 
          File.open(path, 'wb') do |f|
            f.write(params[:logo_file].read)
          end

          params[:logo_file] = nil
        end
        ###########

        # Obtener user del ceo para enviarle la notificacion
        ceo_id = 0;
        auxList = CourseUser.where(:course => product.team.course)
        auxList.each do |auxCU|  
          if auxCU.rol == "CEO" # Es decir donde el rol es CEO
            ceo_id = auxCU.user.id
          end
        end

        currUser = User.find(params[:user_id])

        ##############################
        tokens = FcmToken.where(:user_id => ceo_id)

        if tokens.length > 0 && tokens[0] != nil
          uri = URI('https://fcm.googleapis.com/fcm/send')
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true
          req = Net::HTTP::Post.new(uri.path, initheader = {'Content-Type' =>'application/json', 'Authorization' => 'key=AAAAe3BYdgo:APA91bF13EtVd07IZdv-9XTSATSwd-d1J1n2gKjVWpppTuz7Uj1R2hnwTCL3ioL4e7F4YVhU-iMzDI66Czu9mRT3A9sqQ-HVmb24wyda-lwEukaL7eCLjJHAvnEsi8foZ2_Bsh44wtN8'})

          req.body = {:to => tokens[0].token,

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_edit_form.html.erb
<%= form_for(@product, remote: true) do |f| %>
  <div class="modal-content">
    <div class="input-field ">
      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>
    </div>
    <div class="input-field ">
      <%= f.label :description, "Descripción" %>
      <%= f.text_field :description %>
    </div>
    <div class="input-field ">
      <%= f.label :initials, "Iniciales" %>
      <%= f.text_field :initials %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Guardar", class: "btn" %>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat grey lighten-1" >Cancelar</a> 
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product, remote: true) do |f| %>
  <div class="modal-content">
    <%= hidden_field_tag 'product[team_id]', @team.id %> 
    <div class="input-field ">
      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>
    </div>
    <div class="input-field ">
      <%= f.label :description, "Descripción" %>
      <%= f.text_field :description %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Guardar", class: "btn" %>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat grey lighten-1" >Cancelar</a> 
  </div>
<% end %>

app/views/products/_product.html.erb
<%= link_to( product_path product.id ) do %> 
  <li class="collection-item avatar">
    <img src="/assets/typewriter-01.svg" alt="user_boy" class= "circle">
    <span class="title"> <%=product.name%> </span>
  </li>
<%end%>

app/views/products/_product_sidebar.html.erb
<div style="width: 100%; height: 100%; overflow: auto;">
  <div class="wrapper-image-square">
    <%= image_tag "typewriter-01.svg"%>
  </div>
  <div style="position: relative; padding: 20px;">
    <%if is_leader?(current_user.id, @product.team.course.id) and is_member_team?(current_user.id, @product.team_id) %>
      <%= link_to( "#modal_edit_product", class:"btn-floating blue", style:"position: absolute; top: -20px; right: 5px;") do %>
        <i class="material-icons">mode_edit</i> 
      <% end %>
    <%end%>
    <div style="margin-bottom: : 10px;">
      <span style="font-weight: bold; color: #424242; font-size: 28px;"><%= @product.name%></span>
    </div>
    <div>
      <%= link_to( team_path @product.team.id ) do %>
        <span><%= @product.team.name %></span>
      <%end%>
    </div>
    <div class="">
      <%= @product.description %>
    </div>
  </div>
</div>

app/views/products/_select_prototype_form.html.erb
<form accept-charset="UTF-8" action="<%= products_path %>" class="col s12"
            id="select_prototype" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input name="authenticity_token" type="hidden"
         value="<%= form_authenticity_token %>" />    
  <div class="modal-content">  
    
  </div>
  <div class="modal-footer">
    <button class="btn waves-effect waves-light" type="submit" name="select_prototype">Listo
    </button>
    <a href="#!" data-turbolinks="false" class=" modal-action modal-close waves-effect waves-green btn-flat red lighten-2" >Cancelar</a> 
  </div>
</form>

app/views/products/create.js.erb
var errors_product = <%= @product.errors.count %>;

if(errors_product > 0){
  console.log("NO se creo el equipo");
  
}else{

  $('#modal_new_product').modal('close');
  $('#modal_new_product').find('form input[type="text"]').val('');
  $('div#team_products .collection').prepend("<%= j render @product %>");  
}

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<% content_for :sidebar_option do %>
  <%= render "product_sidebar" %>
<% end %>

<% content_for :bar_option do %>
  <ul class="tabs">
    <li class="tab hide-on-med-and-up"><a href="#product_information" style="outline: none;">información</a></li>
    <li class="tab"><a id="get_product_commitments" class="active" href="#product_commitments" style="outline: none;">compromisos</a></li>
    <li class="tab"><a id="get_my_tasks" class="active" href="#my_tasks" style="outline: none;">mis tareas</a></li>
  </ul>      
<% end %>

<div id="product_id" data-id = "<%= @product.id %>" style="display: none;"></div>
<div id="user_id_tasks" data-id = "<%= current_user.id %>" style="display: none;"></div>

<div id="product_information">
  informacion del producto
</div>
<div id="product_commitments">
  Aqui los compromisos del producto
  <ul class="collection">    
  </ul>

  <div class="fixed-action-btn vertical click-to-toggle">
    <a href="#modal_new_commitment" class="btn-floating btn-large tooltipped indigo" data-position="left" data-delay="50" data-tooltip="Nuevo compromiso">
      <i class="material-icons">add</i>
    </a>
  </div>
</div>

<div id="my_tasks">
  Mis tareas
  <ul class="collection">    
  </ul>
</div>

<!-- Modal Structure - Edit product -->
<div id="modal_edit_product" class="modal">
  <h5 style="padding-left: 20px;">Editar producto</h5>
  <%= render "edit_form" %>
</div>

<!-- Modal Structure - New commitment -->
<div id="modal_new_commitment" class="modal">
  <h5 style="padding-left: 20px;">Editar producto</h5>
  <%= render "commitments/form" %>
</div>

app/views/products/update.js.erb
var errors = <%= @product.errors.count %>;

if(errors > 0){
  console.log("NO se actualizo el curso");
  
}else{

  $('#modal_edit_product').modal('close'); // Función definida en course.js
  $('.sidebar').empty();
  $('.sidebar').html("<%= escape_javascript (render partial: 'product_sidebar') %>"); 
}